### ISSUE TITLE
The notification should be issued only for new projects available

### ISSUE THREAD

**Issue by jeandersonbc** [brenopolanski/notifier-for-udacity-reviewer#15]
I think it's a little annoying when I'm working in a review but the extension keeps displaying the alert message.

The case is even worse if I attempt to open the dashboard page because my browser started to open new tabs exhaustively. I almost lost my ongoing review because chrome was about to crash.

I will work in a patch to fix this.

Another thing more related to UX: I think it would be better if the notification was in the bottom of the browser instead of the top-right corner because when it is opened, it hides the buttons on that area.

**Comment by brenopolanski** [comment]
yeah @jeandersonbc :+1:
