### ISSUE TITLE
When using your package, cant visit the web of udacity

### ISSUE THREAD

**Issue by lilincpp** [brenopolanski/notifier-for-udacity-reviewer#19]
I'm sure my network is fine, but I can not access it

**Comment by brenopolanski** [comment]
hey @lilincpp you can't visit this page >> https://review.udacity.com/#!/submissions/dashboard  ?

**Comment by lilincpp** [comment]
@brenopolanski Yes！But if i click the icon
![1](https://cloud.githubusercontent.com/assets/11869672/19582803/0c0e3292-976a-11e6-81db-3f160c9ca8a0.PNG)

, i can visit dashboard.

**Comment by brenopolanski** [comment]
Hey @lilincpp I did a some tests here and this working fine for me :)

![demo](https://cloud.githubusercontent.com/assets/1894191/19629642/75b83c42-994f-11e6-90bf-161dd972f19c.gif)

**Comment by brenopolanski** [comment]
hey @lilincpp you have some news? it is working for you?

**Comment by lilincpp** [comment]
@brenopolanski Thanks for caring! I found that is caused by my network. Thanks again.

**Comment by brenopolanski** [comment]
Okay :+1:
