### ISSUE TITLE
 just check automatically project in English.

### ISSUE THREAD

**Issue by celibertojr** [brenopolanski/notifier-for-udacity-reviewer#20]
I work with projects in Portuguese (only) even I choosing the language to "Portuguese Pt-BR" the app only check automatically project in English.

**Comment by brenopolanski** [comment]
Hey @celibertojr

Strange... Because when you choose in `select multiple` just **Pt-BR**, the extension will only get reviews in Portuguese.

### Example:

![screenshot from 2016-11-22 09-27-41](https://cloud.githubusercontent.com/assets/1894191/20523890/141a6056-b096-11e6-8d7d-2df10da6cfd6.png)

**Comment by brenopolanski** [comment]
hey @celibertojr  you have some news? it is working for you?

**Comment by celibertojr** [comment]
Without changes. But this kind of problem only happens when having a lot of review waiting (english)  in the queue.

**Comment by brenopolanski** [comment]
okay @celibertojr. i'll do some tests.

**Comment by brenopolanski** [comment]
Closed... because I don't see a problem. Thanks for your report :+1:
